name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "Multi-Camera-Recorder" recorder2.py
        
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Multi-Camera-Recorder-Windows
        path: dist/Multi-Camera-Recorder.exe
        
    - name: Create Release (optional)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/Multi-Camera-Recorder.exe
